export enum ERROR_TYPES {
  'UNAUTHORIZED' = 'UNAUTHORIZED',
  'BAD_REQUEST' = 'BAD_REQUEST',
  'NOT_FOUND' = 'NOT_FOUND'
}

export enum ERROR_CODES {
  'UNAUTHORIZED' = 401,
  'BAD_REQUEST' = 400,
  'NOT_FOUND' = 404,
  'NOT_IMPLEMENTED' = 500
}
